"""Interactive configuration wizard for Solar Dashboard."""

from __future__ import annotations

import getpass
import os
import shutil
import tempfile
from datetime import datetime
from pathlib import Path

from dotenv import dotenv_values

PROJECT_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = PROJECT_DIR / ".env"
EXAMPLE_FILE = PROJECT_DIR / ".env.example"

SETTING_ORDER = (
    "FRONIUS_IP",
    "ELECTRICITY_PRICE_PER_KWH",
    "FEED_IN_TARIFF_PER_KWH",
    "CURRENCY_SYMBOL",
    "WATTPILOT_IP",
    "WATTPILOT_PASSWORD",
    "DATABASE_PATH",
    "POLESTAR_EMAIL",
    "POLESTAR_PASSWORD",
    "POLESTAR_VIN",
    "SIMULATION_MODE",
    "SIMULATION_DATABASE_PATH",
    "HOST",
    "PORT",
)

COMMENTS = {
    "FRONIUS_IP": "Fronius inverter",
    "ELECTRICITY_PRICE_PER_KWH": "Energy prices",
    "WATTPILOT_IP": "Optional Wattpilot",
    "DATABASE_PATH": "Storage",
    "POLESTAR_EMAIL": "Optional Polestar",
    "SIMULATION_MODE": "Simulation",
    "HOST": "Local web server",
}


def load_values(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    return {
        key: value or ""
        for key, value in dotenv_values(path).items()
        if key is not None
    }


def validate_non_empty(value: str) -> str:
    if not value.strip():
        raise ValueError("A value is required.")
    return value.strip()


def validate_host(value: str) -> str:
    value = validate_non_empty(value)
    if "://" in value or any(character.isspace() for character in value):
        raise ValueError("Enter only an IP address or hostname, without http://.")
    return value


def validate_non_negative_number(value: str) -> str:
    value = validate_non_empty(value)
    try:
        number = float(value)
    except ValueError as error:
        raise ValueError("Enter a number, for example 0.30.") from error
    if number < 0:
        raise ValueError("The value cannot be negative.")
    return value


def validate_port(value: str) -> str:
    value = validate_non_empty(value)
    try:
        port = int(value)
    except ValueError as error:
        raise ValueError("Enter a whole-number port.") from error
    if not 1 <= port <= 65535:
        raise ValueError("The port must be between 1 and 65535.")
    return str(port)


def prompt_value(
    label: str,
    current: str,
    *,
    validator=validate_non_empty,
    secret: bool = False,
) -> str:
    while True:
        if secret:
            hint = " [configured]" if current else ""
            entered = getpass.getpass(f"{label}{hint}: ")
        else:
            hint = f" [{current}]" if current else ""
            entered = input(f"{label}{hint}: ")

        value = entered if entered else current
        try:
            return validator(value)
        except ValueError as error:
            print(f"  {error}")


def prompt_bool(label: str, current: bool) -> bool:
    default = "Y/n" if current else "y/N"
    while True:
        answer = input(f"{label} [{default}]: ").strip().lower()
        if not answer:
            return current
        if answer in {"y", "yes"}:
            return True
        if answer in {"n", "no"}:
            return False
        print("  Enter y or n.")


def quote_value(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
    )
    return f'"{escaped}"'


def render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/configure.py",
        "# Re-run the wizard whenever settings change.",
        "",
    ]
    for key in SETTING_ORDER:
        if key in COMMENTS:
            if lines[-1] != "":
                lines.append("")
            lines.append(f"# {COMMENTS[key]}")
        lines.append(f"{key}={quote_value(values.get(key, ''))}")
    return "\n".join(lines) + "\n"


def save_env(path: Path, content: str) -> Path | None:
    backup = None
    if path.exists() and path.read_text() != content:
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup = path.with_name(f"{path.name}.backup-{timestamp}")
        shutil.copy2(path, backup)

    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    os.replace(temporary_path, path)
    return backup


def configure() -> None:
    defaults = load_values(EXAMPLE_FILE)
    existing = load_values(ENV_FILE)
    values = {**defaults, **existing}

    print("\nSolar Dashboard setup")
    print("=====================")
    print("Press Return to keep the value shown in brackets.\n")

    simulation = prompt_bool(
        "Use simulation mode", values.get("SIMULATION_MODE", "false").lower() == "true"
    )
    values["SIMULATION_MODE"] = str(simulation).lower()

    if not simulation:
        values["FRONIUS_IP"] = prompt_value(
            "Fronius IP address", values.get("FRONIUS_IP", ""), validator=validate_host
        )

    values["ELECTRICITY_PRICE_PER_KWH"] = prompt_value(
        "Electricity price per kWh",
        values.get("ELECTRICITY_PRICE_PER_KWH", "0.30"),
        validator=validate_non_negative_number,
    )
    values["FEED_IN_TARIFF_PER_KWH"] = prompt_value(
        "Feed-in tariff per kWh",
        values.get("FEED_IN_TARIFF_PER_KWH", "0.08"),
        validator=validate_non_negative_number,
    )
    values["CURRENCY_SYMBOL"] = prompt_value(
        "Currency symbol", values.get("CURRENCY_SYMBOL", "€")
    )

    wattpilot_enabled = prompt_bool(
        "Configure Wattpilot",
        bool(values.get("WATTPILOT_IP") and values.get("WATTPILOT_PASSWORD")),
    )
    if wattpilot_enabled:
        values["WATTPILOT_IP"] = prompt_value(
            "Wattpilot IP address",
            values.get("WATTPILOT_IP", ""),
            validator=validate_host,
        )
        values["WATTPILOT_PASSWORD"] = prompt_value(
            "Wattpilot password",
            values.get("WATTPILOT_PASSWORD", ""),
            secret=True,
        )
    else:
        values["WATTPILOT_IP"] = values["WATTPILOT_PASSWORD"] = ""

    polestar_enabled = prompt_bool(
        "Configure Polestar",
        bool(values.get("POLESTAR_EMAIL") and values.get("POLESTAR_PASSWORD")),
    )
    if polestar_enabled:
        values["POLESTAR_EMAIL"] = prompt_value(
            "Polestar account email", values.get("POLESTAR_EMAIL", "")
        )
        values["POLESTAR_PASSWORD"] = prompt_value(
            "Polestar password",
            values.get("POLESTAR_PASSWORD", ""),
            secret=True,
        )
        values["POLESTAR_VIN"] = prompt_value(
            "Polestar VIN (optional)",
            values.get("POLESTAR_VIN", ""),
            validator=lambda value: value.strip(),
        )
    else:
        values["POLESTAR_EMAIL"] = ""
        values["POLESTAR_PASSWORD"] = ""
        values["POLESTAR_VIN"] = ""

    if prompt_bool("Configure advanced paths and web-server settings", False):
        values["DATABASE_PATH"] = prompt_value(
            "Database path", values.get("DATABASE_PATH", "instance/solar_dashboard.db")
        )
        values["SIMULATION_DATABASE_PATH"] = prompt_value(
            "Simulation database path",
            values.get("SIMULATION_DATABASE_PATH", "instance/simulation.db"),
        )
        values["HOST"] = prompt_value(
            "Web-server host",
            values.get("HOST", "127.0.0.1"),
            validator=validate_host,
        )
        values["PORT"] = prompt_value(
            "Web-server port", values.get("PORT", "8000"), validator=validate_port
        )
    else:
        values["DATABASE_PATH"] = (
            values.get("DATABASE_PATH") or "instance/solar_dashboard.db"
        )
        values["SIMULATION_DATABASE_PATH"] = (
            values.get("SIMULATION_DATABASE_PATH") or "instance/simulation.db"
        )
        values["HOST"] = values.get("HOST") or "127.0.0.1"
        values["PORT"] = values.get("PORT") or "8000"

    print("\nConfiguration summary")
    print(f"  Mode: {'simulation' if simulation else 'live inverter'}")
    print(f"  Wattpilot: {'enabled' if wattpilot_enabled else 'disabled'}")
    print(f"  Polestar: {'enabled' if polestar_enabled else 'disabled'}")
    print(f"  Dashboard: http://{values['HOST']}:{values['PORT']}")

    if not prompt_bool("Save these settings", True):
        print("No changes were saved.")
        return

    backup = save_env(ENV_FILE, render_env(values))
    print(f"\nSaved configuration to {ENV_FILE}")
    if backup:
        print(f"Previous configuration backed up to {backup}")
    print("You can now start Solar Dashboard.")


if __name__ == "__main__":
    try:
        configure()
    except (EOFError, KeyboardInterrupt):
        print("\nSetup cancelled.")
